name: conditionals
on:
  workflow_dispatch:

jobs:
  conditionals:
    runs-on: self-hosted
    steps:
      - name: runs only when the branch is "main"
        run: 
        if: github.head_ref == 'refs/head/practice'
      - name: runs only on if the previous step failed
        run: 
        if: failure()
      - name: A job that only runs on push events, not on pull requests
        run: 
        if:  github.event_name == 'push'
