name: docker-installations in Multi-OS
on:
  workflow_dispatch:

jobs:
  docker-installations:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    runs-on: "${{ matrix.os}}"
    steps:
      - name: docker-installations "${{ matrix.os}}"
        run: sudo apt update && sudo apt install -y docker.io
      - name: verify installation "${{matrix.os}}"
        run: docker --version
      - name: adding the ubuntu user to docker
        run: sudo usermod -aG docker $USER
