name: Docker Installation Multi OS

on:
  workflow_dispatch:

jobs:
  docker-installations:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check Docker version
        run: docker --version

      - name: Run hello-world container
        run: docker run hello-world
