name: output
on:
  workflow_dispatch:

jobs:
  set-date:
    runs-on: self-hosted
    outputs:
       date: ${{ steps.get_date.outputs.today }}
    steps:
      - name: Set today's date as output
        id: get_date
        run: echo "today=$(date)" >> $GITHUB_OUTPUT

  prints-output:
    runs-on: self-hosted
    needs: set-date
    steps:
      - name: printing the output
        run: echo ${{ needs.set-date.outputs.date }}
