name: self-hosted runner
on: 
  workflow_dispatch: 

jobs:
  self-runner-jobs:
    runs-on: [self-hosted, my-self-hosted-runner]
    steps:
      - name: jobs runner
        run: hostname -I && pwd
      - name: create a file & verify the file exists
        run: touch hello.txt
      - name: enter a message
        run: echo "hello, this file is for testing purpose" > hello.txt
      - name: verify the file exists
        run: cat hello.txt
  
