name: multi-jobs
on:  
  workflow_dispatch:

jobs:
  ubuntu-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: OS name
        run: uname -a && hostname && whoami
      - name: prints the dependency versions
        run: docker --version && python --version && node --version && git --version
  windows-jobs:
    runs-on:  windows-latest
    steps:
      - name: OS name
        shell: powershell
        run: |
          Write-Host "OS: Windows"
          hostname
          whoami
  macos-jobs:
    runs-on: macos-latest
    steps: 
      - name: OS name
        run: uname -a && hostname && whoami
