name: hello
on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out code
        uses: actions/checkout@v4

      - name: Hello from GitHub Actions
        run: echo "Hello from GitHub Actions"
