name: task-1
on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out code
        uses: actions/checkout@v4

      - name: Hello from GitHub Actions
        run: echo "Hello from GitHub Actions"

      - name: current date & timeout
        run: date

      - name: prints the branch name which triggered pipeline
        run: echo "${{ github.ref_name }}"

      - name: List the files in the repo
        run: ls -la

      - name: Print the runner's operating system
        run: uname -a

      - name: test command
        run: I love you
        
